"""
Authoritative tests for chapter-12, lifted out of network.py.

Generated by tools/extract-pb-checks.py — do not edit by hand. The book keeps
these assertions in the same file as the code they grade, which makes them
student-writable; here they are not.
"""

from unittest import TestCase

# Brings in the function under test plus whatever network.py imports at module
# level, which is what the test bodies below reach for.
from network import *  # noqa: F401,F403


class GetDataMessageTest(TestCase):

    def test_serialize(self):
        hex_msg = '020300000030eb2540c41025690160a1014c577061596e32e426b712c7ca00000000000000030000001049847939585b0652fba793661c361223446b6fc41089b8be00000000000000'
        get_data = GetDataMessage()
        block1 = bytes.fromhex('00000000000000cac712b726e4326e596170574c01a16001692510c44025eb30')
        get_data.add_data(FILTERED_BLOCK_DATA_TYPE, block1)
        block2 = bytes.fromhex('00000000000000beb88910c46f6b442312361c6693a7fb52065b583979844910')
        get_data.add_data(FILTERED_BLOCK_DATA_TYPE, block2)
        self.assertEqual(get_data.serialize().hex(), hex_msg)
