"""
Authoritative tests for chapter-12, lifted out of bloomfilter.py.

Generated by tools/extract-pb-checks.py — do not edit by hand. The book keeps
these assertions in the same file as the code they grade, which makes them
student-writable; here they are not.
"""

from unittest import TestCase

# Brings in the function under test plus whatever bloomfilter.py imports at module
# level, which is what the test bodies below reach for.
from bloomfilter import *  # noqa: F401,F403


class BloomFilterTest(TestCase):

    def test_add(self):
        bf = BloomFilter(10, 5, 99)
        item = b'Hello World'
        bf.add(item)
        expected = '0000000a080000000140'
        self.assertEqual(bf.filter_bytes().hex(), expected)
        item = b'Goodbye!'
        bf.add(item)
        expected = '4000600a080000010940'
        self.assertEqual(bf.filter_bytes().hex(), expected)

    def test_filterload(self):
        bf = BloomFilter(10, 5, 99)
        item = b'Hello World'
        bf.add(item)
        item = b'Goodbye!'
        bf.add(item)
        expected = '0a4000600a080000010940050000006300000001'
        self.assertEqual(bf.filterload().serialize().hex(), expected)
