export enum ServiceStatus {
    HEALTHY = 'HEALTHY',
}

export enum CohortType {
    MASTERING_BITCOIN = 'MASTERING_BITCOIN',
    LEARNING_BITCOIN_FROM_COMMAND_LINE = 'LEARNING_BITCOIN_FROM_COMMAND_LINE',
    PROGRAMMING_BITCOIN = 'PROGRAMMING_BITCOIN',
    BITCOIN_PROTOCOL_DEVELOPMENT = 'BITCOIN_PROTOCOL_DEVELOPMENT',
    MASTERING_LIGHTNING_NETWORK = 'MASTERING_LIGHTNING_NETWORK',
}

export enum UserRole {
    ADMIN = 'ADMIN',
    TEACHING_ASSISTANT = 'TEACHING_ASSISTANT',
    STUDENT = 'STUDENT',
}

export enum CertificateType {
    PARTICIPANT = 'PARTICIPANT',
    PERFORMER = 'PERFORMER',
}

export enum TopPerformerRank {
    FIRST = 1,
    SECOND = 2,
    THIRD = 3,
}

export enum CohortWeekType {
    ORIENTATION = 'ORIENTATION',
    GROUP_DISCUSSION = 'GROUP_DISCUSSION',
    GRADUATION = 'GRADUATION',
}
