export enum APITaskStatus {
    UNPROCESSED = 'UNPROCESSED',
    PROCESSING = 'PROCESSING',
    PROCESSED = 'PROCESSED',
    FAILED = 'FAILED',
    CANCELLED = 'CANCELLED',
}

export enum TaskType {
    ASSIGN_COHORT_ROLE = 'ASSIGN_COHORT_ROLE',
    ASSIGN_COHORT_ALUMNI_ROLE = 'ASSIGN_COHORT_ALUMNI_ROLE',
    RECONCILE_COHORT_DISCORD_ROLES = 'RECONCILE_COHORT_DISCORD_ROLES',
    SYNC_CLASSROOM_SCORES = 'SYNC_CLASSROOM_SCORES',
    SEND_COHORT_REMINDER_EMAILS = 'SEND_COHORT_REMINDER_EMAILS',
    SEND_CERTIFICATE_EMAILS = 'SEND_CERTIFICATE_EMAILS',
    SEND_FEEDBACK_REMINDER_EMAILS = 'SEND_FEEDBACK_REMINDER_EMAILS',
    SEND_CALENDAR_UPDATE_EMAILS = 'SEND_CALENDAR_UPDATE_EMAILS',
    SEND_FELLOWSHIP_REPORT_REMINDER_EMAILS = 'SEND_FELLOWSHIP_REPORT_REMINDER_EMAILS',
    PROVISION_ASSIGNMENT_REPO = 'PROVISION_ASSIGNMENT_REPO',
    RECONCILE_CI_RUN = 'RECONCILE_CI_RUN',
    ARCHIVE_ASSIGNMENT_REPOS = 'ARCHIVE_ASSIGNMENT_REPOS',
}
