"""
Authoritative tests for chapter-4, lifted out of helper.py.

Generated by tools/extract-pb-checks.py — do not edit by hand. The book keeps
these assertions in the same file as the code they grade, which makes them
student-writable; here they are not.
"""

from unittest import TestCase

# Brings in the function under test plus whatever helper.py imports at module
# level, which is what the test bodies below reach for.
from helper import *  # noqa: F401,F403


class HelperTest(TestCase):

    def test_little_endian_to_int(self):
        h = bytes.fromhex('99c3980000000000')
        want = 10011545
        self.assertEqual(little_endian_to_int(h), want)
        h = bytes.fromhex('a135ef0100000000')
        want = 32454049
        self.assertEqual(little_endian_to_int(h), want)

    def test_int_to_little_endian(self):
        n = 1
        want = b'\x01\x00\x00\x00'
        self.assertEqual(int_to_little_endian(n, 4), want)
        n = 10011545
        want = b'\x99\xc3\x98\x00\x00\x00\x00\x00'
        self.assertEqual(int_to_little_endian(n, 8), want)
