#!/usr/bin/env python3
"""
Generate authoritative test modules for a programming-bitcoin assignment.

    tools/extract-pb-checks.py <template-repo> <suite-dir>
    tools/extract-pb-checks.py ~/…/pb-week-6-assignment tests/pb-week-6

Jacobs' book puts each `TestCase` in the same file as the function it tests, so
`op.py` holds both `op_checkmultisig` and the `OpTest` that grades it. "Make the
test pass" and "edit the test" are the same edit, and every pb assignment is
shaped that way — 51 exercises across the seven weeks.

This lifts those classes into `fixtures/chapter-N/grader_checks_<module>.py`,
which `restore_fixtures` then drops beside the student's code. The tests run
against whatever they wrote; the assertions are ours.

`from <module> import *` supplies the names each test body reaches for — the
function under test, plus whatever the module imported at its top. One generated
file per source module, so `op.py` and `tx.py` cannot collide.

Which tests matter comes from the notebook, not from the file: a chapter's
module often carries the whole book's suite, and only the cells the student is
asked to run are this week's exercises.
"""

import ast
import json
import pathlib
import re
import sys

RUN_CALL = re.compile(r'run\((\w+)\.(\w+)\(\s*["\'](\w+)["\']\s*\)\)')

HEADER = '''"""
Authoritative tests for {chapter}, lifted out of {module}.py.

Generated by tools/extract-pb-checks.py — do not edit by hand. The book keeps
these assertions in the same file as the code they grade, which makes them
student-writable; here they are not.
"""

from unittest import TestCase

# Brings in the function under test plus whatever {module}.py imports at module
# level, which is what the test bodies below reach for.
from {module} import *  # noqa: F401,F403
'''


def notebook_specs(chapter_dir):
    """Every `run(module.Class("test"))` the chapter's notebook executes."""
    specs = []
    for notebook in sorted(chapter_dir.glob('*.ipynb')):
        if '.ipynb_checkpoints' in str(notebook):
            continue
        for cell in json.loads(notebook.read_text())['cells']:
            for match in RUN_CALL.finditer(''.join(cell['source'])):
                specs.append(match.groups())
    return specs


def extract(chapter_dir, module, wanted):
    """Source of the named TestCase classes in <module>.py."""
    source = (chapter_dir / f'{module}.py').read_text()
    tree = ast.parse(source)

    found = {}
    for node in tree.body:
        if isinstance(node, ast.ClassDef) and node.name in wanted:
            found[node.name] = ast.get_source_segment(source, node)

    missing = wanted - set(found)
    if missing:
        raise SystemExit(
            f'{chapter_dir.name}/{module}.py: no such class: {", ".join(sorted(missing))}'
        )
    # Emit in the order the file declares them, not the order the notebook
    # happens to call them, so the generated file reads like the original.
    return [found[node.name] for node in tree.body
            if isinstance(node, ast.ClassDef) and node.name in wanted]


def main(argv):
    if len(argv) != 3:
        print(__doc__.strip(), file=sys.stderr)
        return 2

    repo = pathlib.Path(argv[1]).expanduser()
    suite = pathlib.Path(argv[2])
    if not repo.is_dir():
        raise SystemExit(f'No template repo at {repo}')

    all_specs = []
    for chapter_dir in sorted(repo.glob('chapter-*')):
        specs = notebook_specs(chapter_dir)
        if not specs:
            continue

        by_module = {}
        for module, class_name, test in specs:
            by_module.setdefault(module, set()).add(class_name)

        out_dir = suite / 'fixtures' / chapter_dir.name
        out_dir.mkdir(parents=True, exist_ok=True)

        for module, classes in sorted(by_module.items()):
            body = extract(chapter_dir, module, classes)
            target = out_dir / f'grader_checks_{module}.py'
            target.write_text(
                HEADER.format(chapter=chapter_dir.name, module=module)
                + '\n\n'
                + '\n\n\n'.join(body)
                + '\n'
            )
            print(f'  wrote {target} ({len(body)} class(es))')

        for module, class_name, test in specs:
            all_specs.append(
                (chapter_dir.name, f'grader_checks_{module}:{class_name}:{test}')
            )

    manifest = suite / 'checks.json'
    manifest.write_text(json.dumps(
        [{'chapter': c, 'spec': s} for c, s in all_specs], indent=2) + '\n')
    print(f'  wrote {manifest} ({len(all_specs)} checks)')
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv))
